### ISSUE TITLE
README enhancements

### ISSUE THREAD

**Issue by sagar-viradiya** [sagar-viradiya/eazypermissions#25]
Move the introduction to Coroutines, LiveData and Kotlin DSL in the individual README file within the respective module.

**Comment by neetigyachahar** [comment]
Will try to do it.
If I am not wrong, coroutinespermission, dslpermission and livedatapermission are those respective modules. Right?

**Comment by sagar-viradiya** [comment]
Yes. Let the top portion till Coroutines support be in top-level README.

**Comment by sagar-viradiya** [comment]
Thanks for submitting PR. I will review once I am free.
