### ISSUE TITLE
ERROR: Failed to resolve: com.sagar:common:2.0.2

### ISSUE THREAD

**Issue by ochkarik05** [sagar-viradiya/eazypermissions#35]
Can't build project with version 2.0.2, because of:
`
ERROR: Failed to resolve: com.sagar:common:2.0.2
`

`
dependencies{
...
    implementation 'com.sagar:coroutinespermission:2.0.2'
...
}
`

Version 2.0.1 works correctly, but I need to update because of #18

**Comment by sagar-viradiya** [comment]
@ochkarik05 Thanks for reporting. Currently, I am addressing the version conflict issue so this should be resolved soon.

**Comment by sagar-viradiya** [comment]
@ochkarik05 Should have been fixed now.
